apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-web-app
  name: simple-web-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-app
    spec:
      containers:
      - image: quay.io/rguske/simple-web-app:v1
        name: simple-web-app
        envFrom:
        - configMapRef:
            name: simple-web-app-config
        ports:
        - containerPort: 8080
        resources: {}
status: {}
